CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_Roles" (
        "Id" text NOT NULL,
        "Description" text,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Abb_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_Users" (
        "Id" text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "RegDate" timestamp with time zone NOT NULL,
        "Role" integer,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Abb_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "BankOperations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "TheSumm" double precision NOT NULL,
        "PayDate" timestamp with time zone NOT NULL,
        "IsPayable" boolean NOT NULL,
        CONSTRAINT "PK_BankOperations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Countdowns" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "EndTime" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Countdowns" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "SiteRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TheName" text NOT NULL,
        "Email" text NOT NULL,
        "Subject" text NOT NULL,
        "Question" text NOT NULL,
        "Created" timestamp with time zone NOT NULL,
        "Status" text NOT NULL,
        CONSTRAINT "PK_SiteRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_Abb_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Abb_RoleClaims_Abb_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Abb_Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_Abb_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Abb_UserClaims_Abb_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Abb_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_Abb_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_Abb_UserLogins_Abb_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Abb_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_UserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_Abb_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_Abb_UserRoles_Abb_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Abb_Roles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Abb_UserRoles_Abb_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Abb_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Abb_UserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_Abb_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_Abb_UserTokens_Abb_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Abb_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "WordCollections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "WordsCollection" jsonb,
        "AuthorId" text NOT NULL,
        "Title" text NOT NULL,
        "PubDate" timestamp with time zone,
        "UpdDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_WordCollections" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WordCollections_Abb_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Abb_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "WordHistories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Word" text NOT NULL,
        "Correct" boolean NOT NULL,
        "IdentityUserId" text NOT NULL,
        "AnswerTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_WordHistories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WordHistories_Abb_Users_IdentityUserId" FOREIGN KEY ("IdentityUserId") REFERENCES "Abb_Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE TABLE "Blogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Preview" text NOT NULL,
        "TheText" text NOT NULL,
        "ImageUrl" text NOT NULL,
        "CategoryId" integer,
        "IsDeleted" boolean NOT NULL,
        "Title" text NOT NULL,
        "PubDate" timestamp with time zone,
        "UpdDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Blogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Blogs_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    INSERT INTO "Categories" ("Id", "Name")
    VALUES (1, 'Lifestyle');
    INSERT INTO "Categories" ("Id", "Name")
    VALUES (2, 'Sport');
    INSERT INTO "Categories" ("Id", "Name")
    VALUES (3, 'Software Development');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    INSERT INTO "Blogs" ("Id", "CategoryId", "ImageUrl", "IsDeleted", "Preview", "PubDate", "TheText", "Title", "UpdDate")
    VALUES (1, 1, 'imageUrl', FALSE, 'Vitafit Digital Personal Scales for People, Weighing Professional since 2001, Body Scales with Clear LED Display and Step-On, 180 kg, Batteries Included, Silver Black…', NULL, 'HIGH PRECISION GUARANTEE With more than 20 years experience in the scale industry, we have developed the scale with the best technology and expertise, guaranteeing high accuracy of 0.1lb/0.05kg throughout the life of the scale.
    Easy to use: the scale people uses up-to-date digital technology, along with many friendly functions, including: auto calibration, auto step up, auto power off, convenient large platform in 280 x 280 mm, 3 x AAA batteries included, 3 unit switch: lb/kg/st, and high precision in full weighing range.', 'My first blog post from dbcontext migration', TIMESTAMPTZ '2025-09-24T05:47:43.884405Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_Abb_RoleClaims_RoleId" ON "Abb_RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "Abb_Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_Abb_UserClaims_UserId" ON "Abb_UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_Abb_UserLogins_UserId" ON "Abb_UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_Abb_UserRoles_RoleId" ON "Abb_UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "EmailIndex" ON "Abb_Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Abb_Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_Blogs_CategoryId" ON "Blogs" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_WordCollections_AuthorId" ON "WordCollections" ("AuthorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    CREATE INDEX "IX_WordHistories_IdentityUserId" ON "WordHistories" ("IdentityUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Blogs"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Blogs") + 1,
            nextval(pg_get_serial_sequence('"Blogs"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924054748_initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250924054748_initial', '8.0.12');
    END IF;
END $EF$;
COMMIT;

